mode: remote
identifier: server
category: devops
username: root

jobs:
  - stages:
      - name: Setup and Clone
        tasks:
          setup_and_clone:
            enabled: true
            branches: [master]
            clone_dir: "/tmp/sample_rake_project"
            source_url: "https://github.com/deeeye2/sample_rake_project.git"

      - name: Rake Build
        tasks:
          rake:
            enabled: true
            task: "build"
